version: '3.8'

services:
  # PHP-FPM
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"

  # MySQL
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "5306:3306"

  # Nginx
  nginx:
    image: nginx:latest
    platform: linux/amd64
    container_name: laravel_nginx
    ports:
      - "8088:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www
